/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#0e0e0e',
        surface: '#0e0e0e',
        'surface-dim': '#0e0e0e',
        'surface-bright': '#2c2c2c',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#131313',
        'surface-container': '#1a1919',
        'surface-container-high': '#201f1f',
        'surface-container-highest': '#262626',
        'surface-variant': '#262626',
        'surface-tint': '#86adff',
        'on-surface': '#ffffff',
        'on-surface-variant': '#adaaaa',
        'inverse-surface': '#fcf8f8',
        'inverse-on-surface': '#565554',
        primary: '#86adff',
        'primary-container': '#6f9fff',
        'primary-dim': '#006fef',
        'primary-fixed': '#6f9fff',
        'primary-fixed-dim': '#5491ff',
        'on-primary': '#002c67',
        'on-primary-container': '#002150',
        'inverse-primary': '#005ac5',
        secondary: '#8b94ff',
        'secondary-container': '#0011fe',
        'secondary-dim': '#5461ff',
        'secondary-fixed': '#ccceff',
        'secondary-fixed-dim': '#bbbfff',
        'on-secondary': '#000478',
        'on-secondary-container': '#d7d8ff',
        tertiary: '#69fd5d',
        'tertiary-container': '#59ee50',
        'tertiary-dim': '#49e043',
        'on-tertiary': '#005e07',
        error: '#ff6e84',
        'error-container': '#a70138',
        'error-dim': '#d73357',
        'on-error': '#490013',
        'on-error-container': '#ffb2b9',
        outline: '#777575',
        'outline-variant': '#494847',
      },
      fontFamily: {
        display: ['"Space Grotesk"', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['3.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'display-md': ['3rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'display-sm': ['2.25rem', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        'headline-lg': ['2rem', { lineHeight: '1.25' }],
        'headline-md': ['1.5rem', { lineHeight: '1.3' }],
        'headline-sm': ['1.25rem', { lineHeight: '1.4' }],
        'body-lg': ['1rem', { lineHeight: '1.6' }],
        'body-md': ['0.875rem', { lineHeight: '1.5' }],
        'body-sm': ['0.75rem', { lineHeight: '1.5' }],
        'label-sm': ['0.75rem', { lineHeight: '1.4', letterSpacing: '0.05rem' }],
      },
      borderRadius: {
        sm: '2px',
        DEFAULT: '4px',
        lg: '8px',
        xl: '16px',
      },
      boxShadow: {
        window: '0px 20px 40px rgba(0, 17, 255, 0.08)',
        'glow-primary': '0 0 20px rgba(134, 173, 255, 0.15)',
        'glow-tertiary': '0 0 20px rgba(105, 253, 93, 0.15)',
      },
      backgroundImage: {
        'cta-gradient': 'linear-gradient(135deg, #86adff 0%, #0011fe 100%)',
        scanline: 'repeating-linear-gradient(0deg, rgba(0,0,0,0.02) 0px, rgba(0,0,0,0.02) 1px, transparent 1px, transparent 2px)',
      },
    },
  },
  plugins: [],
}
