export const BIOS_LINES: string[] = [
  'Ghost Shell OS v1.0.0',
  'Copyright (c) 2026 Laurian Duma. All rights reserved.',
  '',
  'BIOS version 0.1.0-alpha',
  'Detecting hardware...',
  'CPU: Creative Engine v8 @ 3.2GHz',
  'RAM: 16384MB [OK]',
  'GPU: Obsidian Renderer [OK]',
  '',
  'Initializing kernel...',
  'Loading window manager... [OK]',
  'Loading terminal emulator... [OK]',
  'Loading filesystem... [OK]',
  '',
  'Mounting /dev/portfolio...',
  '> /about         [OK]',
  '> /projects      [OK]',
  '> /experience    [OK]',
  '> /hobbies       [OK]',
  '> /contact       [OK]',
  '',
  'All systems nominal.',
  'Booting desktop environment...',
]
